server:
  port: 64413

spring:
  application:
    name: notice-service

eureka:
  instance:
    instance-id: notice-microservice-instance

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka